version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:16.04

    environment:
      HIFI_VCPKG_BASE: /home/circleci/hifi-vcpkg
      CCACHE_DIR: /home/circleci/.ccache
      USE_CCACHE: True

    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y ccache python3 libssl-dev mesa-utils libpulse0 libnss3 libnspr4 libfontconfig1 libxcursor1 libxcomposite1 libxtst6 libxslt1.1 libasound2 libxmu-dev libxi-dev freeglut3-dev libasound2-dev libjack0 libjack-dev libxrandr-dev libudev-dev libssl-dev zlib1g-dev

      - run:
          name: Install cmake
          command: |
            wget https://cmake.org/files/v3.14/cmake-3.14.2-Linux-x86_64.sh
            sudo sh cmake-3.14.2-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir

      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run:
          name: Download VCPKG deps
          command: |
            mkdir -p $HIFI_VCPKG_BASE
            cd $HIFI_VCPKG_BASE
            wget https://hifi-content.s3-us-west-1.amazonaws.com/clement/dev/vcpkg.tar.gz
            tar -xf vcpkg.tar.gz

      - restore_cache:
          keys:
            - build-cache-v1-{{ .Branch }}-{{ .Revision }}
            - build-cache-v1-{{ .Branch }}-
            - build-cache-v1-

      - run:
          name: Setup workspace
          command: |
            cmake -E make_directory /home/circleci/project/build
            mkdir -p $CCACHE_DIR

      - run:
          name: Run cmake
          working_directory: /home/circleci/project/build
          command: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCLIENT_ONLY=ON -DBUILD_SERVER=OFF -DBUILD_TESTS=OFF -DBUILD_TOOLS=OFF /home/circleci/project

      - run:
          name: Build Interface
          command: cmake --build /home/circleci/project/build --target interface -- -j2

      - run:
          name: CCache stats
          command: ccache -s

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "/home/circleci/.ccache"
